airstats:
  outputs:
    staging:
      type: duckdb
      path: "airstats.duckdb"
      schema: "dbt_{{ env_var('DBT_ENV_NAME') | lower | trim }}_staging"
      threads: 4

    prod:
      type: duckdb
      path: "airstats.duckdb"
      schema: "dbt_{{ env_var('DBT_ENV_NAME') | lower | trim }}_prod"
      threads: 4

    dev:
      type: duckdb
      path: "airstats.duckdb"
      schema: "dbt_{{ env_var('DBT_ENV_NAME') | lower | trim }}_dev"
      threads: 4

  target: dev
